name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        name: Code quality checks
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Set up node
              uses: actions/setup-node@v1
              with:
                  node-version: '14'
            - name: Install dependencies
              run: npm install
            - name: Lint
              run: npm run lint
            - name: Check formatting
              run: npm run format:check
